using System;
using MigraDoc.DocumentObjectModel;

namespace SimplePdfReport.Reporting.MigraDoc.Internal
{
    internal class HeaderAndFooter
    {
        public void Add(Section section, ReportData data)
        {
            AddHeader(section, data.Patient, data.Plans);
            AddFooter(section, data.User);
        }

        private void AddHeader(Section section, Patient patient, Plans plans)
        {
            var header = section.Headers.Primary.AddParagraph();
			header.Style = StyleNames.Header;
            header.Format.AddTabStop(Size.GetWidth(section), TabAlignment.Right);

            header.AddText($"{patient.Name} ({patient.Id})");
            header.AddTab();
            header.AddText(plans.Id);
        }

        private void AddFooter(Section section, User user)
        {
            var footer = section.Footers.Primary.AddParagraph();
			footer.Style = StyleNames.Footer;
            footer.Format.AddTabStop(Size.GetWidth(section), TabAlignment.Right);

            footer.AddText($"Generated by {user.Username} at {DateTime.Now:g}");
            footer.AddTab();
            footer.AddText("Page ");
            footer.AddPageField();
            footer.AddText(" of ");
            footer.AddNumPagesField();
        }
    }
}